apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

nameSuffix: -prod

labels:
- includeSelectors: true
  pairs:
    app: stormpiper-prod
images:
- name: gcr.io/tacoma-app/stormpiper-pod
  newName: gcr.io/tacoma-app/stormpiper-pod
  newTag: latest
- name: gcr.io/tacoma-app/bg_worker
  newName: gcr.io/tacoma-app/bg_worker
  newTag: latest
- name: gcr.io/tacoma-app/redis
  newName: gcr.io/tacoma-app/redis
  newTag: latest
